name: flutter_dev_camp_london
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  go_router: ^13.2.0
  intl: ^0.18.0
  provider: ^6.1.1
  json_annotation: ^4.8.1

  # My Custom Packages
  flutter_ui_plants:
    path: packages/flutter_ui_plants
  flutter_to_do:
    path: packages/flutter_to_do
  flutter_json_serializable:
    path: packages/flutter_json_serializable

dev_dependencies:
  bloc_test: ^9.1.4
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  generate: true
  assets:
  - assets/images/
